# Generated by Django 4.0.2 on 2022-02-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResColl', '0003_response_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='angle',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='cumcum_resid_30',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
