# Generated by Django 3.2.3 on 2022-03-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResColl', '0004_response_angle_response_cumcum_resid_30'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='cumcum_resid_30',
            new_name='cumsum_resid_30',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='residual_sd',
            new_name='sd_residual',
        ),
    ]
